version: "3.8"

services:
  kokoro-fastapi:
    image: ghcr.io/remsky/kokoro-fastapi-gpu  # ✅ Ensure GPU version
    container_name: kokoro-fastapi
    runtime: nvidia  # ✅ Explicitly set NVIDIA runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # ✅ Allow access to all GPUs
      - NVIDIA_DRIVER_CAPABILITIES=all  # ✅ Provide all driver capabilities
    ports:
      - "8880:8880"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  # ✅ Ensure GPU is used

  gradio-kokoro:
    build: .
    container_name: gradio-kokoro
    depends_on:
      - kokoro-fastapi
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://kokoro-fastapi:8880/v1
